(()=>{const u=new URL(window.location.href);let changed=false;for(const k of [...u.searchParams.keys()]){const n=k.toLowerCase();if(n.startsWith('utm_')||['gclid','fbclid','mc_cid','mc_eid'].includes(n)){u.searchParams.delete(k);changed=true}}if(changed)history.replaceState(null,'',u.pathname+(u.search||'')+u.hash)})();
const BASE=document.documentElement.dataset.base||'./';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const path=p=>BASE+String(p||'').replace(/^\.\//,'');
const initials=n=>String(n||'').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
let profiles=[];
function setupNav(){const btn=$('.nav-toggle'),nav=$('.main-nav');if(!btn||!nav)return;btn.addEventListener('click',()=>{nav.classList.toggle('open');btn.setAttribute('aria-expanded',nav.classList.contains('open'))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')))}
function publicationCard(p){return `<article class="publication-card"><p class="eyebrow">${esc(p.type)} · ${esc(p.category)} · ${esc(p.date_label)}</p><h3><a href="${esc(path(p.href))}">${esc(p.title)}</a></h3><p>${esc(p.summary)}</p><div class="publication-foot"><span class="status">${esc(p.status)}</span><a class="text-link" href="${esc(path(p.href))}">Leer nota →</a></div></article>`}
async function initPublications(){const host=$('#latest-publications');if(!host)return;try{const r=await fetch(path('data/publications.json'));if(!r.ok)throw new Error(`HTTP ${r.status}`);const items=await r.json();host.innerHTML=items.map(publicationCard).join('')||'<p class="muted">Todavía no hay publicaciones.</p>'}catch(err){host.innerHTML='<p>No se pudo cargar el archivo de publicaciones.</p>';console.error(err)}}
function badgeClass(v){if(v==='Verificado 2026')return '';if(v==='Parcial')return 'partial';if(v==='Último dato anterior')return 'old';return 'no'}
function avatar(p){return p.photo_local?`<img class="avatar" src="${esc(path(p.photo_local))}" alt="Retrato público verificado de ${esc(p.name)}" loading="lazy">`:`<div class="avatar" aria-label="Sin foto pública verificada">${esc(initials(p.name))}</div>`}
function renderDirectory(){const search=$('#search'),type=$('#type-filter'),verify=$('#verification-filter'),host=$('#profiles'),count=$('#result-count');if(!search||!type||!verify||!host)return;const q=search.value.trim().toLowerCase(),t=type.value,v=verify.value;const filtered=profiles.filter(p=>{const hay=[p.name,p.name_published,p.type,p.role,p.jurisdiction,p.workplace].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!t||p.type===t)&&(!v||p.verification_level===v)});if(count)count.textContent=`${filtered.length} de ${profiles.length}`;host.innerHTML=filtered.map(p=>`<article class="card" tabindex="0" data-n="${p.n}" aria-label="Abrir ficha de ${esc(p.name)}"><div class="card-top">${avatar(p)}<div><p class="eyebrow">${esc(p.type||'Sin categoría')}</p><h3>${esc(p.name)}</h3><p class="role">${esc(p.role||p.workplace||'')}</p></div></div><span class="badge ${badgeClass(p.verification_level)}">${esc(p.verification_level||'Sin nivel')}</span></article>`).join('')||'<p>No hay resultados para estos filtros.</p>';host.querySelectorAll('.card').forEach(c=>{const open=()=>showProfile(+c.dataset.n);c.addEventListener('click',open);c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})})}
function field(label,value){return value?`<div class="field"><span>${esc(label)}</span><p>${esc(value)}</p></div>`:''}
function sourceLink(label,url){if(!url)return '';try{const u=new URL(url);if(!/^https?:$/.test(u.protocol))return ''}catch{return ''}return `<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`}
function showProfile(n){const p=profiles.find(x=>x.n===n),dialog=$('#profile-dialog'),detail=$('#profile-detail');if(!p||!dialog||!detail)return;detail.innerHTML=`<article class="detail"><div class="detail-head">${avatar(p)}<div><p class="eyebrow">Ficha #${p.n} · ${esc(p.type||'Sin categoría')}</p><h2>${esc(p.name)}</h2><span class="status ${p.verification_level==='Verificado 2026'?'verified':''}">${esc(p.verification_level)}</span>${p.photo_local?`<p class="photo-credit">Retrato: ${esc(p.photo_note||'fuente pública verificada')}</p>`:'<p class="photo-credit">Sin foto pública verificada.</p>'}</div></div><div class="detail-grid">${field('Nombre publicado',p.name_published)}${field('Cargo',p.role)}${field('Fuero / organismo',p.jurisdiction)}${field('Dependencia',p.workplace)}${field('Dirección laboral pública',p.work_address)}${field('Teléfono institucional',p.work_phone)}${field('Email institucional',p.work_email)}${field('Desde cuándo',p.since)}${field('Mecanismo de designación',p.appointment)}${field('Estado de verificación',p.verification_status)}${field('Notas',p.notes)}</div><div class="sources"><p class="eyebrow">Fuentes</p>${sourceLink('Fuente principal',p.source_primary)}${sourceLink('Fuente adicional',p.source_additional)}${sourceLink('Fuente del retrato',p.photo_source)}</div></article>`;dialog.showModal()}
async function initDirectory(){const host=$('#profiles');if(!host)return;try{const[pr,st]=await Promise.all([fetch(path('data/profiles.json')),fetch(path('data/stats.json'))]);if(!pr.ok||!st.ok)throw new Error('No se pudo cargar la base');profiles=await pr.json();const stats=await st.json();if($('#stat-total'))$('#stat-total').textContent=stats.total;if($('#stat-verified'))$('#stat-verified').textContent=stats.verified_2026;if($('#stat-photos'))$('#stat-photos').textContent=stats.photos_verified;const type=$('#type-filter');[...new Set(profiles.map(p=>p.type).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es')).forEach(t=>type.insertAdjacentHTML('beforeend',`<option>${esc(t)}</option>`));['search','type-filter','verification-filter'].forEach(id=>{const el=$('#'+id);if(el)el.addEventListener('input',renderDirectory)});const close=$('.close'),dialog=$('#profile-dialog');if(close&&dialog){close.addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()})}renderDirectory()}catch(err){host.innerHTML='<p>No se pudo cargar el directorio.</p>';console.error(err)}}
setupNav();initPublications();initDirectory();
