(()=>{const u=new URL(location.href),keys=['utm_source','utm_medium','utm_campaign','utm_content','utm_term','gclid','fbclid','mc_cid','mc_eid'];const now={};for(const k of keys){const v=u.searchParams.get(k);if(v)now[k]=v}try{if(Object.keys(now).length)sessionStorage.setItem('ltp_campaign',JSON.stringify(now));window.LTP_CAMPAIGN=JSON.parse(sessionStorage.getItem('ltp_campaign')||'{}')}catch{window.LTP_CAMPAIGN=now}let changed=false;for(const k of [...u.searchParams.keys()]){const n=k.toLowerCase();if(n.startsWith('utm_')||['gclid','fbclid','mc_cid','mc_eid'].includes(n)){u.searchParams.delete(k);changed=true}}if(changed)history.replaceState(null,'',u.pathname+(u.search||'')+u.hash)})();
const BASE=document.documentElement.dataset.base||'./';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const path=p=>BASE+String(p||'').replace(/^\.\//,'');
const initials=n=>String(n||'').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
let profiles=[];
const INTEREST_TOPICS=['Economía y bolsillo','Política y Estado','Justicia y seguridad','Impuestos y trámites','Trabajo y jubilaciones','Salud','Educación','Servicios públicos y transporte','Clima y ambiente','Tecnología e inteligencia artificial','Deportes','Provincia y municipios','Sociedad','Documentos públicos','Investigaciones'];
let publications=[];
function setupNav(){const btn=$('.nav-toggle'),nav=$('.main-nav');if(!btn||!nav)return;btn.addEventListener('click',()=>{nav.classList.toggle('open');btn.setAttribute('aria-expanded',nav.classList.contains('open'))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')))}
function publicationCard(p){const tags=(p.topics||[]).map(t=>`<span class="topic-tag">${esc(t)}</span>`).join('');return `<article class="publication-card"><p class="eyebrow">${esc(p.type)} · ${esc(p.category)} · ${esc(p.date_label)}</p><h3><a href="${esc(path(p.href))}">${esc(p.title)}</a></h3><p>${esc(p.summary)}</p>${tags?`<div class="topic-tags">${tags}</div>`:''}<div class="publication-foot"><span class="status">${esc(p.status)}</span><a class="text-link" href="${esc(path(p.href))}">Leer nota →</a></div></article>`}
function renderPublications(topic=''){const host=$('#latest-publications');if(!host)return;const items=topic?publications.filter(p=>(p.topics||[]).includes(topic)):publications;host.innerHTML=items.map(publicationCard).join('')||`<p class="muted">Todavía no hay publicaciones en <strong>${esc(topic)}</strong>.</p>`;const label=$('#publication-filter-label');if(label)label.textContent=topic?`Filtrando por: ${topic}`:'Todas las publicaciones.';document.querySelectorAll('[data-topic]').forEach(b=>{const active=(b.dataset.topic||'')===topic;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))})}
function renderTopics(){const host=$('#interest-topics');if(!host)return;host.innerHTML=`<button class="topic-button active" type="button" data-topic="" aria-pressed="true">Todos</button>`+INTEREST_TOPICS.map(t=>`<button class="topic-button" type="button" data-topic="${esc(t)}" aria-pressed="false">${esc(t)}</button>`).join('');host.addEventListener('click',e=>{const b=e.target.closest('[data-topic]');if(b)renderPublications(b.dataset.topic||'')})}
async function initPublications(){const host=$('#latest-publications');if(!host)return;try{const r=await fetch(path('data/publications.json'));if(!r.ok)throw new Error(`HTTP ${r.status}`);publications=await r.json();renderTopics();renderPublications()}catch(err){host.innerHTML='<p>No se pudo cargar el archivo de publicaciones.</p>';console.error(err)}}
function badgeClass(v){if(v==='Verificado 2026')return '';if(v==='Parcial')return 'partial';if(v==='Último dato anterior')return 'old';return 'no'}
function avatar(p){return p.photo_local?`<img class="avatar" src="${esc(path(p.photo_local))}" alt="Retrato público verificado de ${esc(p.name)}" loading="lazy">`:`<div class="avatar" aria-label="Sin foto pública verificada">${esc(initials(p.name))}</div>`}
function renderDirectory(){const search=$('#search'),type=$('#type-filter'),verify=$('#verification-filter'),host=$('#profiles'),count=$('#result-count');if(!search||!type||!verify||!host)return;const q=search.value.trim().toLowerCase(),t=type.value,v=verify.value;const filtered=profiles.filter(p=>{const hay=[p.name,p.name_published,p.type,p.role,p.jurisdiction,p.workplace].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!t||p.type===t)&&(!v||p.verification_level===v)});if(count)count.textContent=`${filtered.length} de ${profiles.length}`;host.innerHTML=filtered.map(p=>`<article class="card" tabindex="0" data-n="${p.n}" aria-label="Abrir ficha de ${esc(p.name)}"><div class="card-top">${avatar(p)}<div><p class="eyebrow">${esc(p.type||'Sin categoría')}</p><h3>${esc(p.name)}</h3><p class="role">${esc(p.role||p.workplace||'')}</p></div></div><span class="badge ${badgeClass(p.verification_level)}">${esc(p.verification_level||'Sin nivel')}</span></article>`).join('')||'<p>No hay resultados para estos filtros.</p>';host.querySelectorAll('.card').forEach(c=>{const open=()=>showProfile(+c.dataset.n);c.addEventListener('click',open);c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})})}
function field(label,value){return value?`<div class="field"><span>${esc(label)}</span><p>${esc(value)}</p></div>`:''}
function sourceLink(label,url){if(!url)return '';try{const u=new URL(url);if(!/^https?:$/.test(u.protocol))return ''}catch{return ''}return `<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`}
function showProfile(n){const p=profiles.find(x=>x.n===n),dialog=$('#profile-dialog'),detail=$('#profile-detail');if(!p||!dialog||!detail)return;detail.innerHTML=`<article class="detail"><div class="detail-head">${avatar(p)}<div><p class="eyebrow">Ficha #${p.n} · ${esc(p.type||'Sin categoría')}</p><h2>${esc(p.name)}</h2><span class="status ${p.verification_level==='Verificado 2026'?'verified':''}">${esc(p.verification_level)}</span>${p.photo_local?`<p class="photo-credit">Retrato: ${esc(p.photo_note||'fuente pública verificada')}</p>`:'<p class="photo-credit">Sin foto pública verificada.</p>'}</div></div><div class="detail-grid">${field('Nombre publicado',p.name_published)}${field('Cargo',p.role)}${field('Fuero / organismo',p.jurisdiction)}${field('Dependencia',p.workplace)}${field('Dirección laboral pública',p.work_address)}${field('Teléfono institucional',p.work_phone)}${field('Email institucional',p.work_email)}${field('Desde cuándo',p.since)}${field('Mecanismo de designación',p.appointment)}${field('Estado de verificación',p.verification_status)}${field('Notas',p.notes)}</div><div class="sources"><p class="eyebrow">Fuentes</p>${sourceLink('Fuente principal',p.source_primary)}${sourceLink('Fuente adicional',p.source_additional)}${sourceLink('Fuente del retrato',p.photo_source)}</div></article>`;dialog.showModal()}
async function initDirectory(){const host=$('#profiles');if(!host)return;try{const[pr,st]=await Promise.all([fetch(path('data/profiles.json')),fetch(path('data/stats.json'))]);if(!pr.ok||!st.ok)throw new Error('No se pudo cargar la base');profiles=await pr.json();const stats=await st.json();if($('#stat-total'))$('#stat-total').textContent=stats.total;if($('#stat-verified'))$('#stat-verified').textContent=stats.verified_2026;if($('#stat-photos'))$('#stat-photos').textContent=stats.photos_verified;const type=$('#type-filter');[...new Set(profiles.map(p=>p.type).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es')).forEach(t=>type.insertAdjacentHTML('beforeend',`<option>${esc(t)}</option>`));['search','type-filter','verification-filter'].forEach(id=>{const el=$('#'+id);if(el)el.addEventListener('input',renderDirectory)});const close=$('.close'),dialog=$('#profile-dialog');if(close&&dialog){close.addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()})}renderDirectory()}catch(err){host.innerHTML='<p>No se pudo cargar el directorio.</p>';console.error(err)}}
setupNav();initPublications();initDirectory();

function setupLanguageSwitch(){const masthead=document.querySelector('.masthead');if(!masthead||masthead.querySelector('.language-switch'))return;const root=document.documentElement;const isEn=(root.lang||'').toLowerCase().startsWith('en');const esHref=root.dataset.esHref||(!isEn?window.location.pathname+window.location.search:BASE);const enHref=root.dataset.enHref||(isEn?window.location.pathname+window.location.search:path('en/'));const box=document.createElement('div');box.className='language-switch';box.setAttribute('aria-label',isEn?'Language':'Idioma');const ar='<svg class="flag-svg" viewBox="0 0 30 20" aria-hidden="true"><rect width="30" height="20" fill="#74acdf"/><rect y="6.66" width="30" height="6.68" fill="#fff"/><circle cx="15" cy="10" r="1.7" fill="#f6b40e"/></svg><span class="sr-only">Español (Argentina)</span>';const us='<svg class="flag-svg" viewBox="0 0 30 20" aria-hidden="true"><rect width="30" height="20" fill="#fff"/><path fill="#b22234" d="M0 0h30v1.54H0zm0 3.08h30v1.54H0zm0 3.08h30V7.7H0zm0 3.08h30v1.54H0zm0 3.08h30v1.54H0zm0 3.08h30v1.54H0zm0 3.08h30V20H0z"/><rect width="13" height="10.8" fill="#3c3b6e"/><g fill="#fff"><circle cx="2" cy="2" r=".55"/><circle cx="5" cy="2" r=".55"/><circle cx="8" cy="2" r=".55"/><circle cx="11" cy="2" r=".55"/><circle cx="3.5" cy="4.5" r=".55"/><circle cx="6.5" cy="4.5" r=".55"/><circle cx="9.5" cy="4.5" r=".55"/><circle cx="2" cy="7" r=".55"/><circle cx="5" cy="7" r=".55"/><circle cx="8" cy="7" r=".55"/><circle cx="11" cy="7" r=".55"/></g></svg><span class="sr-only">English (United States)</span>';const es=isEn?`<a href="${esc(esHref)}" lang="es-AR" title="Español (Argentina)">${ar}</a>`:`<span class="active" lang="es-AR" title="Español (Argentina)">${ar}</span>`;const en=!isEn?`<a href="${esc(enHref)}" lang="en-US" title="English (United States)">${us}</a>`:`<span class="active" lang="en-US" title="English (United States)">${us}</span>`;box.innerHTML=es+en;const nav=masthead.querySelector('.main-nav');masthead.insertBefore(box,nav||null)}
setupLanguageSwitch();

const LTP_ANALYTICS_ENDPOINT='https://dttvbpcjbvqtwfzbxohb.supabase.co/functions/v1/record-analytics';
function ltpVisitorId(){try{const k='ltp_visitor_v1',ttl=30*864e5,n=Date.now();let x=JSON.parse(localStorage.getItem(k)||'null');if(!x||!x.id||n-x.created>ttl){x={id:crypto.randomUUID(),created:n};localStorage.setItem(k,JSON.stringify(x))}return x.id}catch{return crypto.randomUUID()}}
function ltpReferrerHost(){try{return document.referrer?new URL(document.referrer).hostname:''}catch{return ''}}
function ltpDeviceClass(){const w=Math.min(screen.width||innerWidth,innerWidth||screen.width);return w<768?'mobile':w<1100?'tablet':'desktop'}
function ltpTrackAudience(eventType='pageview',target=''){const c=window.LTP_CAMPAIGN||{},body={event_type:eventType,path:location.pathname,article_slug:document.documentElement.dataset.articleKey||null,visitor_id:ltpVisitorId(),referrer_host:ltpReferrerHost(),utm_source:c.utm_source||null,utm_medium:c.utm_medium||null,utm_campaign:c.utm_campaign||null,utm_content:c.utm_content||null,locale:navigator.language||null,device_class:ltpDeviceClass(),target:target||null};fetch(LTP_ANALYTICS_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),keepalive:true}).catch(()=>{})}
function ltpTrackedUrl(source){const c=document.querySelector('link[rel="canonical"]')?.href||location.href,u=new URL(c);u.searchParams.set('utm_source',source);u.searchParams.set('utm_medium','social');u.searchParams.set('utm_campaign','article_share');u.searchParams.set('utm_content',document.documentElement.dataset.articleKey||'article');return u.toString()}
function setupArticleSharing(){const k=document.documentElement.dataset.articleKey;if(!k)return;const main=document.querySelector('main');if(!main||document.querySelector('.article-share'))return;const title=document.querySelector('meta[property="og:title"]')?.content||document.title,clean=document.querySelector('link[rel="canonical"]')?.href||location.href,isEn=(document.documentElement.lang||'').startsWith('en');const labels=isEn?{title:'Share this article',wa:'WhatsApp',x:'X',tg:'Telegram',native:'Share',copy:'Copy link',copied:'Copied'}:{title:'Compartir esta nota',wa:'WhatsApp',x:'X',tg:'Telegram',native:'Compartir',copy:'Copiar enlace',copied:'Copiado'};const box=document.createElement('section');box.className='article-share section';box.innerHTML=`<div class="wrap narrow"><p class="eyebrow">${labels.title}</p><div class="share-actions"><a data-share="whatsapp" target="_blank" rel="noopener noreferrer">${labels.wa}</a><a data-share="x" target="_blank" rel="noopener noreferrer">${labels.x}</a><a data-share="telegram" target="_blank" rel="noopener noreferrer">${labels.tg}</a><button type="button" data-share="native">${labels.native}</button><button type="button" data-share="copy">${labels.copy}</button></div></div>`;main.append(box);const links={whatsapp:`https://wa.me/?text=${encodeURIComponent(title+'\n'+ltpTrackedUrl('whatsapp'))}`,x:`https://twitter.com/intent/tweet?text=${encodeURIComponent(title)}&url=${encodeURIComponent(ltpTrackedUrl('x'))}`,telegram:`https://t.me/share/url?url=${encodeURIComponent(ltpTrackedUrl('telegram'))}&text=${encodeURIComponent(title)}`};for(const [n,u] of Object.entries(links))box.querySelector('[data-share="'+n+'"]').href=u;box.addEventListener('click',async e=>{const el=e.target.closest('[data-share]');if(!el)return;const n=el.dataset.share;ltpTrackAudience('share',n);if(n==='native'){if(navigator.share)await navigator.share({title,url:clean}).catch(()=>{});else await navigator.clipboard.writeText(clean).catch(()=>{})}if(n==='copy'){await navigator.clipboard.writeText(clean).catch(()=>{});el.textContent=labels.copied;setTimeout(()=>el.textContent=labels.copy,1500)}})}
async function setupRelatedArticles(){if(!(document.documentElement.lang||'').startsWith('es')||!document.documentElement.dataset.articleKey)return;const main=document.querySelector('main');if(!main||document.querySelector('.related-stories'))return;try{const r=await fetch(path('data/publications.json'));if(!r.ok)return;const items=await r.json(),key=document.documentElement.dataset.articleKey,cur=items.find(x=>x.slug===key);if(!cur)return;const score=p=>(p.topics||[]).filter(t=>(cur.topics||[]).includes(t)).length;const other=items.filter(x=>x.slug!==key).sort((x,y)=>score(y)-score(x)||y.date.localeCompare(x.date)).slice(0,3);if(!other.length)return;const s=document.createElement('section');s.className='related-stories section';s.innerHTML=`<div class="wrap narrow"><p class="eyebrow">Seguir leyendo</p><h2>Más en La Trama Pública</h2><div class="related-grid">${other.map(p=>`<a href="${esc(path(p.href))}"><strong>${esc(p.title)}</strong><span>${esc(p.category)}</span></a>`).join('')}</div><div class="retention-links"><a href="${esc(path('notas/'))}">Ver todas las notas</a><a href="${esc(path('rss.xml'))}">RSS</a></div></div>`;main.append(s)}catch{}}
setupArticleSharing();setupRelatedArticles();ltpTrackAudience('pageview');
