(()=>{const u=new URL(window.location.href);let changed=false;for(const k of [...u.searchParams.keys()]){const n=k.toLowerCase();if(n.startsWith('utm_')||['gclid','fbclid','mc_cid','mc_eid'].includes(n)){u.searchParams.delete(k);changed=true}}if(changed)history.replaceState(null,'',u.pathname+(u.search||'')+u.hash)})();
let profiles=[];
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const initials=n=>String(n||'').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
function badgeClass(v){if(v==='Verificado 2026')return '';if(v==='Parcial')return 'partial';if(v==='Último dato anterior')return 'old';return 'no'}
function avatar(p){return p.photo_local?`<img class="avatar" src="${esc(p.photo_local)}" alt="Retrato público verificado de ${esc(p.name)}" loading="lazy">`:`<div class="avatar" aria-label="Sin foto pública verificada">${esc(initials(p.name))}</div>`}
function render(){const q=$('#search').value.trim().toLowerCase();const t=$('#type-filter').value;const v=$('#verification-filter').value;const filtered=profiles.filter(p=>{const hay=[p.name,p.name_published,p.type,p.role,p.jurisdiction,p.workplace].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!t||p.type===t)&&(!v||p.verification_level===v)});$('#result-count').textContent=`${filtered.length} de ${profiles.length}`;$('#profiles').innerHTML=filtered.map(p=>`<article class="card" tabindex="0" data-n="${p.n}" aria-label="Abrir ficha de ${esc(p.name)}"><div class="card-top">${avatar(p)}<div><p class="eyebrow">${esc(p.type||'Sin categoría')}</p><h3>${esc(p.name)}</h3><p class="role">${esc(p.role||p.workplace||'')}</p></div></div><span class="badge ${badgeClass(p.verification_level)}">${esc(p.verification_level||'Sin nivel')}</span></article>`).join('')||'<p>No hay resultados para estos filtros.</p>';document.querySelectorAll('.card').forEach(c=>{const open=()=>showProfile(+c.dataset.n);c.addEventListener('click',open);c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})})}
function field(label,value){return value?`<div class="field"><span>${esc(label)}</span><p>${esc(value)}</p></div>`:''}
function sourceLink(label,url){if(!url)return '';try{const u=new URL(url);if(!/^https?:$/.test(u.protocol))return ''}catch{return ''}return `<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`}
function showProfile(n){const p=profiles.find(x=>x.n===n);if(!p)return;$('#profile-detail').innerHTML=`<article class="detail"><div class="detail-head">${avatar(p)}<div><p class="eyebrow">Ficha #${p.n} · ${esc(p.type||'Sin categoría')}</p><h2>${esc(p.name)}</h2><span class="status ${p.verification_level==='Verificado 2026'?'verified':''}">${esc(p.verification_level)}</span>${p.photo_local?`<p class="photo-credit">Retrato: ${esc(p.photo_note||'fuente pública verificada')}</p>`:'<p class="photo-credit">Sin foto pública verificada.</p>'}</div></div><div class="detail-grid">${field('Nombre publicado',p.name_published)}${field('Cargo',p.role)}${field('Fuero / organismo',p.jurisdiction)}${field('Dependencia',p.workplace)}${field('Dirección laboral pública',p.work_address)}${field('Teléfono institucional',p.work_phone)}${field('Email institucional',p.work_email)}${field('Desde cuándo',p.since)}${field('Mecanismo de designación',p.appointment)}${field('Estado de verificación',p.verification_status)}${field('Notas',p.notes)}</div><div class="sources"><p class="eyebrow">Fuentes</p>${sourceLink('Fuente principal',p.source_primary)}${sourceLink('Fuente adicional',p.source_additional)}${sourceLink('Fuente del retrato',p.photo_source)}</div></article>`;$('#profile-dialog').showModal()}
async function init(){const[pr,st]=await Promise.all([fetch('data/profiles.json'),fetch('data/stats.json')]);profiles=await pr.json();const stats=await st.json();$('#stat-total').textContent=stats.total;$('#stat-verified').textContent=stats.verified_2026;$('#stat-photos').textContent=stats.photos_verified;[...new Set(profiles.map(p=>p.type).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es')).forEach(t=>$('#type-filter').insertAdjacentHTML('beforeend',`<option>${esc(t)}</option>`));render()}
['search','type-filter','verification-filter'].forEach(id=>document.addEventListener('input',e=>{if(e.target.id===id)render()}));$('.close').addEventListener('click',()=>$('#profile-dialog').close());$('#profile-dialog').addEventListener('click',e=>{if(e.target===$('#profile-dialog'))$('#profile-dialog').close()});$('.nav-toggle').addEventListener('click',e=>{const n=$('.main-nav');n.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',n.classList.contains('open'))});document.querySelectorAll('.main-nav a').forEach(a=>a.addEventListener('click',()=>$('.main-nav').classList.remove('open')));init().catch(err=>{$('#profiles').innerHTML='<p>No se pudo cargar el directorio.</p>';console.error(err)});

