(()=>{
const cfg=window.LTP_DISCUSSION_CONFIG||{},api=window.supabase?.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const box=$('#auth-box'),dash=$('#dashboard'),status=$('#auth-status'),emailForm=$('#email-form'),codeForm=$('#code-form');
let pendingEmail='';try{pendingEmail=sessionStorage.getItem('ltp_admin_otp_email')||''}catch{}
function setPendingEmail(v){pendingEmail=v;try{if(v)sessionStorage.setItem('ltp_admin_otp_email',v);else sessionStorage.removeItem('ltp_admin_otp_email')}catch{}}
function table(title,rows=[]){return `<section class="section"><h2>${esc(title)}</h2><table class="analytics-table"><thead><tr><th>Valor</th><th>Total</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${Number(r.count)||0}</td></tr>`).join('')||'<tr><td colspan="2">Sin datos</td></tr>'}</tbody></table></section>`}
async function load(){if(!api){status.textContent='Configuración de Supabase no disponible.';return}const {data:{session}}=await api.auth.getSession();if(!session){box.hidden=false;dash.hidden=true;codeForm.hidden=!pendingEmail;emailForm.hidden=!!pendingEmail;$('#auth-logout').hidden=true;return}setPendingEmail('');const {data,error}=await api.rpc('admin_analytics_summary',{p_days:30});if(error){box.hidden=false;dash.hidden=true;$('#auth-logout').hidden=false;status.textContent=error.message.includes('forbidden')?'La cuenta autenticada no tiene rol admin.':error.message;return}box.hidden=true;dash.hidden=false;$('#pageviews').textContent=data.pageviews;$('#visitors').textContent=data.unique_visitors;$('#shares').textContent=data.shares;$('#period').textContent=`${data.days} días`;$('#tables').innerHTML=table('Notas más leídas',data.top_articles)+table('Fuentes / UTM',data.sources)+table('Referentes',data.referrers)+table('Campañas',data.campaigns)+table('Canales compartidos',data.share_targets)+table('Dispositivos',data.devices)}
emailForm.addEventListener('submit',async e=>{e.preventDefault();const email=$('#email').value.trim();if(!email)return;status.textContent='Enviando…';const {error}=await api.auth.signInWithOtp({email,options:{shouldCreateUser:false}});if(error){status.textContent=error.message;return}setPendingEmail(email);emailForm.hidden=true;codeForm.hidden=false;status.textContent='Revisá tu email e ingresá el código de acceso.'});
codeForm.addEventListener('submit',async e=>{e.preventDefault();const token=$('#code').value.replace(/\D/g,'');if(!pendingEmail){status.textContent='Ingresá tu email nuevamente.';return}const {error}=await api.auth.verifyOtp({email:pendingEmail,token,type:'email'});if(error){status.textContent=error.message;return}setPendingEmail('');status.textContent='';await load()});
$('#auth-logout').addEventListener('click',async()=>{await api.auth.signOut();location.reload()});$('#refresh').addEventListener('click',load);$('#logout').addEventListener('click',async()=>{await api.auth.signOut();location.reload()});
api?.auth.onAuthStateChange(()=>setTimeout(load,0));load();
})();
