(()=>{
const cfg=window.LTP_DISCUSSION_CONFIG||{},api=window.supabase?.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=v=>{try{const u=new URL(v);return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}};
const authBox=$('#auth-box'),dash=$('#dashboard'),status=$('#auth-status'),codeForm=$('#code-form'),emailForm=$('#email-form');
let pendingEmail='';try{pendingEmail=sessionStorage.getItem('ltp_admin_otp_email')||''}catch{}
function setPendingEmail(v){pendingEmail=v;try{if(v)sessionStorage.setItem('ltp_admin_otp_email',v);else sessionStorage.removeItem('ltp_admin_otp_email')}catch{}}
function relation(v){return ({confirms:'Confirma',contradicts:'Contradice',context:'Agrega contexto',correction:'Propone corrección',document:'Aporta documento',other:'Otro'})[v]||v}
function state(v){return ({pending:'Recibido',reviewing:'En revisión',verified:'Verificado',rejected:'No incorporado'})[v]||v}
function render(rows){const host=$('#submissions');host.innerHTML=rows.length?rows.map(x=>{const href=safeUrl(x.source_url);const privateContact=x.allow_contact&&x.contact_method&&x.contact_value?`<p><strong>Contacto privado autorizado:</strong> ${esc(x.contact_method)} — ${esc(x.contact_value)}${x.public_contact?' · también público':''}</p>`:'';return `<article class="moderation-card" data-id="${esc(x.id)}"><header><span class="evidence-status status-${esc(x.status)}">${esc(state(x.status))}</span><strong>${esc(x.public_alias)}</strong><time>${new Date(x.created_at).toLocaleString('es-AR')}</time></header><p><strong>${esc(relation(x.relation))}</strong> · ${esc(x.article_slug)}</p><p>${esc(x.summary)}</p>${href?`<p><a href="${esc(href)}" target="_blank" rel="noopener noreferrer">Abrir fuente</a></p>`:''}<p><strong>Crédito elegido:</strong> ${esc(x.credit_name||x.public_alias)}</p>${privateContact}<label>Nota editorial<textarea data-note maxlength="2000">${esc(x.review_note||'')}</textarea></label><div class="moderation-actions"><button type="button" data-status="reviewing">En revisión</button><button type="button" data-status="verified">Verificar</button><button type="button" data-status="rejected">No incorporar</button></div></article>`}).join(''):'<p class="discussion-empty">No hay aportes en este estado.</p>'}
async function load(){if(!api){status.textContent='Configuración de Supabase no disponible.';return}const {data:{session}}=await api.auth.getSession();if(!session){authBox.hidden=false;dash.hidden=true;codeForm.hidden=!pendingEmail;emailForm.hidden=!!pendingEmail;return}setPendingEmail('');const filter=$('#filter').value||null;const {data,error}=await api.rpc('admin_evidence_submissions',{p_status:filter});if(error){authBox.hidden=false;dash.hidden=true;$('#auth-logout').hidden=false;status.textContent=error.message.includes('forbidden')?'La cuenta autenticada no tiene rol admin/moderator.':error.message;return}authBox.hidden=true;dash.hidden=false;render(data||[])}
emailForm.addEventListener('submit',async e=>{e.preventDefault();const email=$('#email').value.trim();status.textContent='Enviando…';const {error}=await api.auth.signInWithOtp({email,options:{shouldCreateUser:false}});if(error){status.textContent=error.message;return}setPendingEmail(email);emailForm.hidden=true;codeForm.hidden=false;status.textContent='Revisá tu email e ingresá el código de acceso.'});
codeForm.addEventListener('submit',async e=>{e.preventDefault();const token=$('#code').value.replace(/\D/g,'');if(!pendingEmail){status.textContent='Ingresá tu email nuevamente.';return}const {error}=await api.auth.verifyOtp({email:pendingEmail,token,type:'email'});if(error){status.textContent=error.message;return}setPendingEmail('');status.textContent='';await load()});
$('#auth-logout').addEventListener('click',async()=>{await api.auth.signOut();location.reload()});
$('#filter').addEventListener('change',load);$('#refresh').addEventListener('click',load);$('#logout').addEventListener('click',async()=>{await api.auth.signOut();location.reload()});
$('#submissions').addEventListener('click',async e=>{const b=e.target.closest('[data-status]');if(!b)return;const card=b.closest('[data-id]');const note=card.querySelector('[data-note]').value.trim()||null;b.disabled=true;const {error}=await api.rpc('moderate_evidence_submission',{p_id:card.dataset.id,p_status:b.dataset.status,p_review_note:note});if(error){alert(error.message);b.disabled=false;return}await load()});
api?.auth.onAuthStateChange(()=>setTimeout(load,0));load();
})();
