(()=>{
const cfg=window.LTP_DISCUSSION_CONFIG||{},api=window.supabase?.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=v=>{try{const u=new URL(v);return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}};
const authBox=$('#auth-box'),dash=$('#dashboard'),status=$('#auth-status'),codeForm=$('#code-form'),emailForm=$('#email-form');
let pendingEmail='';try{pendingEmail=sessionStorage.getItem('ltp_admin_otp_email')||''}catch{}
function setPendingEmail(v){pendingEmail=v;try{if(v)sessionStorage.setItem('ltp_admin_otp_email',v);else sessionStorage.removeItem('ltp_admin_otp_email')}catch{}}
function relation(v){return ({confirms:'Confirma',contradicts:'Contradice',context:'Agrega contexto',correction:'Propone corrección',document:'Aporta documento',other:'Otro'})[v]||v}
function generalType(v){return ({tip:'Dato / pista',source:'Fuente',document:'Documento',correction:'Corrección',investigation:'Propuesta de investigación',other:'Otro'})[v]||v}
function state(v){return ({pending:'Recibido',reviewing:'En revisión',verified:'Verificado',rejected:'No incorporado'})[v]||v}
function renderEvidence(rows){const host=$('#submissions');host.innerHTML=rows.length?rows.map(x=>{const href=safeUrl(x.source_url);const privateContact=x.allow_contact&&x.contact_method&&x.contact_value?`<p><strong>Contacto privado autorizado:</strong> ${esc(x.contact_method)} · ${esc(x.contact_value)}${x.public_contact?' · también público':''}</p>`:'';return `<article class="moderation-card" data-kind="evidence" data-id="${esc(x.id)}"><header><span class="evidence-status status-${esc(x.status)}">${esc(state(x.status))}</span><strong>${esc(x.public_alias)}</strong><time>${new Date(x.created_at).toLocaleString('es-AR')}</time></header><p><strong>${esc(relation(x.relation))}</strong> · ${esc(x.article_slug)}</p><p>${esc(x.summary)}</p>${href?`<p><a href="${esc(href)}" target="_blank" rel="noopener noreferrer">Abrir fuente</a></p>`:''}<p><strong>Crédito elegido:</strong> ${esc(x.credit_name||x.public_alias)}</p>${privateContact}<label>Nota editorial<textarea data-note maxlength="2000">${esc(x.review_note||'')}</textarea></label><div class="moderation-actions"><button type="button" data-status="reviewing">En revisión</button><button type="button" data-status="verified">Verificar</button><button type="button" data-status="rejected">No incorporar</button></div></article>`}).join(''):'<p class="discussion-empty">No hay aportes a notas en este estado.</p>'}
async function renderGeneral(rows){const host=$('#general-submissions');const cards=[];for(const x of rows){const href=safeUrl(x.source_url);let file='';if(x.file_path){const signed=await api.storage.from('contribution-files').createSignedUrl(x.file_path,300);if(!signed.error&&signed.data?.signedUrl)file=`<p><a href="${esc(signed.data.signedUrl)}" target="_blank" rel="noopener noreferrer">Abrir archivo: ${esc(x.file_name||'documento')}</a></p>`}const contact=x.contact_method&&x.contact_value?`<p><strong>Contacto:</strong> ${esc(x.contact_method)} · ${esc(x.contact_value)} · contacto privado ${x.allow_contact?'autorizado':'no autorizado'}${x.public_contact?' · publicación autorizada':''}</p>`:'<p><strong>Contacto:</strong> no informado</p>';cards.push(`<article class="moderation-card" data-kind="general" data-id="${esc(x.id)}"><header><span class="evidence-status status-${esc(x.status)}">${esc(state(x.status))}</span><strong>${esc(generalType(x.contribution_type))}</strong><time>${new Date(x.created_at).toLocaleString('es-AR')}</time></header><h3>${esc(x.topic)}</h3><p>${esc(x.details).replace(/\n/g,'<br>')}</p>${href?`<p><a href="${esc(href)}" target="_blank" rel="noopener noreferrer">Abrir fuente / enlace</a></p>`:''}${file}<p><strong>Colaborador:</strong> ${esc(x.contact_name||'No informado')}</p>${contact}<p><strong>Crédito:</strong> ${x.public_credit?esc(x.credit_name||x.contact_name||'Nombre/alias no informado'):'No publicar crédito'}</p><p><strong>Notificación:</strong> ${esc(x.email_status||'?')}</p><label>Nota editorial<textarea data-note maxlength="2000">${esc(x.review_note||'')}</textarea></label><div class="moderation-actions"><button type="button" data-status="reviewing">En revisión</button><button type="button" data-status="verified">Verificar</button><button type="button" data-status="rejected">No incorporar</button></div></article>`)}host.innerHTML=cards.join('')||'<p class="discussion-empty">No hay información nueva en este estado.</p>'}
async function load(){if(!api){status.textContent='Configuración de Supabase no disponible.';return}const {data:{session}}=await api.auth.getSession();if(!session){authBox.hidden=false;dash.hidden=true;codeForm.hidden=!pendingEmail;emailForm.hidden=!!pendingEmail;return}setPendingEmail('');const filter=$('#filter').value||null;const [general,evidence]=await Promise.all([api.rpc('admin_general_contributions',{p_status:filter}),api.rpc('admin_evidence_submissions',{p_status:filter})]);const error=general.error||evidence.error;if(error){authBox.hidden=false;dash.hidden=true;$('#auth-logout').hidden=false;status.textContent=error.message.includes('forbidden')?'La cuenta autenticada no tiene rol admin/moderator.':error.message;return}authBox.hidden=true;dash.hidden=false;await renderGeneral(general.data||[]);renderEvidence(evidence.data||[])}
emailForm.addEventListener('submit',async e=>{e.preventDefault();const email=$('#email').value.trim();status.textContent='Enviando…';const {error}=await api.auth.signInWithOtp({email,options:{shouldCreateUser:false}});if(error){status.textContent=error.message;return}setPendingEmail(email);emailForm.hidden=true;codeForm.hidden=false;status.textContent='Revisá tu email e ingresá el código de acceso.'});
codeForm.addEventListener('submit',async e=>{e.preventDefault();const token=$('#code').value.replace(/\D/g,'');if(!pendingEmail){status.textContent='Ingresá tu email nuevamente.';return}const {error}=await api.auth.verifyOtp({email:pendingEmail,token,type:'email'});if(error){status.textContent=error.message;return}setPendingEmail('');status.textContent='';await load()});
$('#auth-logout').addEventListener('click',async()=>{await api.auth.signOut();location.reload()});
$('#filter').addEventListener('change',load);$('#refresh').addEventListener('click',load);$('#logout').addEventListener('click',async()=>{await api.auth.signOut();location.reload()});
$('#dashboard').addEventListener('click',async e=>{const b=e.target.closest('[data-status]');if(!b)return;const card=b.closest('[data-id]');const note=card.querySelector('[data-note]').value.trim()||null;const rpc=card.dataset.kind==='general'?'moderate_general_contribution':'moderate_evidence_submission';b.disabled=true;const {error}=await api.rpc(rpc,{p_id:card.dataset.id,p_status:b.dataset.status,p_review_note:note});if(error){alert(error.message);b.disabled=false;return}await load()});
api?.auth.onAuthStateChange(()=>setTimeout(load,0));load();
})();
